-- O Exame (Cabeçalho)
CREATE TABLE public.exams (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    animal_id UUID REFERENCES public.animals(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    machine_id BIGINT REFERENCES public.machines(id) ON DELETE SET NULL,
    exam_type_id BIGINT REFERENCES public.exam_types(id) ON DELETE SET NULL,
    data_exame TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Valores dos Exames (Onde o dado numérico vive)
CREATE TABLE public.exam_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id UUID REFERENCES public.exams(id) ON DELETE CASCADE,
    parameter_id BIGINT REFERENCES public.exam_parameters(id) ON DELETE CASCADE,
    valor DECIMAL NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Garante que não haja dois valores para o mesmo parâmetro no mesmo exame
    UNIQUE(exam_id, parameter_id)
);