-- Cálculos (Relacionamento 1:1 com Exame)
CREATE TABLE public.calculations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id UUID REFERENCES public.exams(id) ON DELETE CASCADE UNIQUE,
    resultado JSONB NOT NULL DEFAULT '{}'::jsonb,
    interpretacao TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para que as buscas fiquem rápidas
CREATE INDEX idx_exams_animal_id ON public.exams(animal_id);
CREATE INDEX idx_exam_values_exam_id ON public.exam_values(exam_id);
CREATE INDEX idx_animals_user_id ON public.animals(user_id);