CREATE TABLE IF NOT EXISTS public.animal_latest_exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id UUID NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    source_file_name TEXT,
    extracted_values JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (animal_id)
);

ALTER TABLE public.animal_latest_exams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own latest exams" ON public.animal_latest_exams;
CREATE POLICY "Users read own latest exams"
ON public.animal_latest_exams
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users insert own latest exams" ON public.animal_latest_exams;
CREATE POLICY "Users insert own latest exams"
ON public.animal_latest_exams
FOR INSERT
WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
        SELECT 1
        FROM public.animals a
        WHERE a.id = animal_id
          AND a.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Users update own latest exams" ON public.animal_latest_exams;
CREATE POLICY "Users update own latest exams"
ON public.animal_latest_exams
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
        SELECT 1
        FROM public.animals a
        WHERE a.id = animal_id
          AND a.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Users delete own latest exams" ON public.animal_latest_exams;
CREATE POLICY "Users delete own latest exams"
ON public.animal_latest_exams
FOR DELETE
USING (auth.uid() = user_id);
