-- Animais
CREATE TABLE public.animals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL,
    animal_type_id BIGINT REFERENCES public.animal_types(id) ON DELETE SET NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Definição dos Parâmetros (Dicionário de parâmetros)
CREATE TABLE public.exam_parameters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    sigla TEXT,
    unidade TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);